// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package shard

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_d1be392e604b0a96, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type UserReq struct {
	ReqUser              int64    `protobuf:"varint,1,opt,name=ReqUser,proto3" json:"ReqUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_d1be392e604b0a96, []int{1}
}
func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (dst *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(dst, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetReqUser() int64 {
	if m != nil {
		return m.ReqUser
	}
	return 0
}

type UserRsp struct {
	OtherUsers           []*User  `protobuf:"bytes,1,rep,name=OtherUsers,proto3" json:"OtherUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRsp) Reset()         { *m = UserRsp{} }
func (m *UserRsp) String() string { return proto.CompactTextString(m) }
func (*UserRsp) ProtoMessage()    {}
func (*UserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_d1be392e604b0a96, []int{2}
}
func (m *UserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRsp.Unmarshal(m, b)
}
func (m *UserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRsp.Marshal(b, m, deterministic)
}
func (dst *UserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRsp.Merge(dst, src)
}
func (m *UserRsp) XXX_Size() int {
	return xxx_messageInfo_UserRsp.Size(m)
}
func (m *UserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserRsp proto.InternalMessageInfo

func (m *UserRsp) GetOtherUsers() []*User {
	if m != nil {
		return m.OtherUsers
	}
	return nil
}

type UserPairRequest struct {
	Uid1                 int64    `protobuf:"varint,1,opt,name=Uid1,proto3" json:"Uid1,omitempty"`
	Uid2                 int64    `protobuf:"varint,2,opt,name=Uid2,proto3" json:"Uid2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPairRequest) Reset()         { *m = UserPairRequest{} }
func (m *UserPairRequest) String() string { return proto.CompactTextString(m) }
func (*UserPairRequest) ProtoMessage()    {}
func (*UserPairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_d1be392e604b0a96, []int{3}
}
func (m *UserPairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPairRequest.Unmarshal(m, b)
}
func (m *UserPairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPairRequest.Marshal(b, m, deterministic)
}
func (dst *UserPairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPairRequest.Merge(dst, src)
}
func (m *UserPairRequest) XXX_Size() int {
	return xxx_messageInfo_UserPairRequest.Size(m)
}
func (m *UserPairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserPairRequest proto.InternalMessageInfo

func (m *UserPairRequest) GetUid1() int64 {
	if m != nil {
		return m.Uid1
	}
	return 0
}

func (m *UserPairRequest) GetUid2() int64 {
	if m != nil {
		return m.Uid2
	}
	return 0
}

type IsFiendResp struct {
	IsFriend             bool     `protobuf:"varint,1,opt,name=IsFriend,proto3" json:"IsFriend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsFiendResp) Reset()         { *m = IsFiendResp{} }
func (m *IsFiendResp) String() string { return proto.CompactTextString(m) }
func (*IsFiendResp) ProtoMessage()    {}
func (*IsFiendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_d1be392e604b0a96, []int{4}
}
func (m *IsFiendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsFiendResp.Unmarshal(m, b)
}
func (m *IsFiendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsFiendResp.Marshal(b, m, deterministic)
}
func (dst *IsFiendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsFiendResp.Merge(dst, src)
}
func (m *IsFiendResp) XXX_Size() int {
	return xxx_messageInfo_IsFiendResp.Size(m)
}
func (m *IsFiendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IsFiendResp.DiscardUnknown(m)
}

var xxx_messageInfo_IsFiendResp proto.InternalMessageInfo

func (m *IsFiendResp) GetIsFriend() bool {
	if m != nil {
		return m.IsFriend
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "shard.User")
	proto.RegisterType((*UserReq)(nil), "shard.UserReq")
	proto.RegisterType((*UserRsp)(nil), "shard.UserRsp")
	proto.RegisterType((*UserPairRequest)(nil), "shard.UserPairRequest")
	proto.RegisterType((*IsFiendResp)(nil), "shard.IsFiendResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	UserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) UserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/shard.UserSvc/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	UserInfo(context.Context, *UserReq) (*User, error)
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shard.UserSvc/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).UserInfo(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shard.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfo",
			Handler:    _UserSvc_UserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// RelSvcClient is the client API for RelSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RelSvcClient interface {
	IsFriend(ctx context.Context, in *UserPairRequest, opts ...grpc.CallOption) (*IsFiendResp, error)
	Friends(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRsp, error)
}

type relSvcClient struct {
	cc *grpc.ClientConn
}

func NewRelSvcClient(cc *grpc.ClientConn) RelSvcClient {
	return &relSvcClient{cc}
}

func (c *relSvcClient) IsFriend(ctx context.Context, in *UserPairRequest, opts ...grpc.CallOption) (*IsFiendResp, error) {
	out := new(IsFiendResp)
	err := c.cc.Invoke(ctx, "/shard.RelSvc/IsFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relSvcClient) Friends(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRsp, error) {
	out := new(UserRsp)
	err := c.cc.Invoke(ctx, "/shard.RelSvc/Friends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelSvcServer is the server API for RelSvc service.
type RelSvcServer interface {
	IsFriend(context.Context, *UserPairRequest) (*IsFiendResp, error)
	Friends(context.Context, *UserReq) (*UserRsp, error)
}

func RegisterRelSvcServer(s *grpc.Server, srv RelSvcServer) {
	s.RegisterService(&_RelSvc_serviceDesc, srv)
}

func _RelSvc_IsFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelSvcServer).IsFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shard.RelSvc/IsFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelSvcServer).IsFriend(ctx, req.(*UserPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelSvc_Friends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelSvcServer).Friends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shard.RelSvc/Friends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelSvcServer).Friends(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RelSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shard.RelSvc",
	HandlerType: (*RelSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsFriend",
			Handler:    _RelSvc_IsFriend_Handler,
		},
		{
			MethodName: "Friends",
			Handler:    _RelSvc_Friends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_d1be392e604b0a96) }

var fileDescriptor_rpc_d1be392e604b0a96 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x1b, 0x5b, 0xfb, 0x67, 0x0a, 0x0a, 0x73, 0x28, 0x4b, 0x4f, 0x65, 0xbd, 0xa4, 0x14,
	0x02, 0x46, 0x11, 0xbd, 0x7a, 0xa8, 0xe4, 0xa2, 0xb2, 0xd2, 0x0f, 0x10, 0xbb, 0x53, 0x12, 0xd0,
	0xfc, 0xd9, 0x8d, 0x82, 0xdf, 0x5e, 0x66, 0xb3, 0xd6, 0x15, 0x4f, 0x99, 0xdf, 0xec, 0x9b, 0x79,
	0x6f, 0xb3, 0x30, 0x33, 0xcd, 0x3e, 0x69, 0x4c, 0xdd, 0xd5, 0x78, 0x6a, 0x8b, 0xdc, 0x68, 0x79,
	0x80, 0xd1, 0xce, 0x92, 0xc1, 0x05, 0x8c, 0xf9, 0x9b, 0x69, 0x11, 0xad, 0xa2, 0x78, 0xa8, 0x3c,
	0x21, 0xc2, 0xe8, 0x31, 0x7f, 0x27, 0x71, 0xb2, 0x8a, 0xe2, 0x99, 0x72, 0x35, 0x2e, 0x61, 0x7a,
	0x5f, 0x9a, 0xae, 0xd0, 0xf9, 0x97, 0x18, 0xba, 0xfe, 0x91, 0x79, 0xcf, 0x03, 0x55, 0x9a, 0x8c,
	0x18, 0xb9, 0x13, 0x4f, 0xf2, 0x02, 0x26, 0xbc, 0x51, 0x51, 0x8b, 0x02, 0x26, 0x8a, 0x5a, 0x26,
	0xef, 0xf5, 0x83, 0xf2, 0xc6, 0x8b, 0x6c, 0x83, 0x1b, 0x80, 0xa7, 0xae, 0x20, 0xc3, 0x6c, 0x45,
	0xb4, 0x1a, 0xc6, 0xf3, 0x74, 0x9e, 0xb8, 0xcc, 0x89, 0xd3, 0x04, 0xc7, 0xf2, 0x0e, 0xce, 0xb9,
	0x78, 0xce, 0x4b, 0x36, 0xf8, 0x20, 0xdb, 0x71, 0xee, 0x5d, 0xa9, 0x2f, 0xbd, 0x83, 0xab, 0x7d,
	0x2f, 0x75, 0x77, 0xe9, 0x7b, 0xa9, 0x5c, 0xc3, 0x3c, 0xb3, 0xdb, 0x92, 0x2a, 0xad, 0xc8, 0x36,
	0x7c, 0xb5, 0xcc, 0x6e, 0x0d, 0xb3, 0x1b, 0x9d, 0xaa, 0x23, 0xa7, 0xd7, 0x7d, 0xba, 0x97, 0xcf,
	0x3d, 0xae, 0x61, 0xea, 0xfe, 0x4f, 0x75, 0xa8, 0xf1, 0x2c, 0x4c, 0x45, 0xed, 0x32, 0x4c, 0x29,
	0x07, 0x69, 0x0d, 0x63, 0x45, 0x6f, 0x3c, 0x74, 0xfb, 0xbb, 0x1b, 0x17, 0x81, 0x28, 0x88, 0xbd,
	0x44, 0xdf, 0x0f, 0x32, 0xc9, 0x01, 0x6e, 0x60, 0xd2, 0xcf, 0xd9, 0x7f, 0x6e, 0x7f, 0x98, 0xc5,
	0xaf, 0x63, 0xf7, 0xbe, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xbf, 0xb1, 0x47, 0xec,
	0x01, 0x00, 0x00,
}
