im: ./main --app=im --http_port=8002 --user_grpc_addr=user.local.nutshell:80 --rel_grpc_addr=rel.local.nutshell:80
rel: ./main --app=rel --grpc_port=9002 --user_grpc_addr=user.local.nutshell:80
user: ./main --app=user --http_port=8001 --grpc_port=9001
